events {
    worker_connections 10000;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    error_log /tmp/nginx_error.log debug;
    access_log /tmp/nginx_access.log;

    charset utf-8;

    map $http_upgrade $connection_upgrade {
        default upgrade;
        ''      close;
    }

    server {
        listen 8181;
        server_name localhost;


        location /legacy {
            return 301 /api/v1;
        }

        location /documentation {
            alias /parking/static/Readme.html;
            default_type text/html;

            add_header Content-Type "text/html; charset=utf-8" always;
            add_header Content-Security-Policy "default-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:;";
        }

        location /management {
            alias /parking/static/management.html;
            default_type text/html;

            add_header Content-Type "text/html; charset=utf-8" always;
            add_header Content-Security-Policy "default-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:;";
        }

        location / {
            root /parking/static;
            try_files $uri $uri/ /index.html;

            location ~* \.html$ {
                add_header Content-Type "text/html; charset=utf-8" always;
            }
        }

        location /reserved {
            return 301 /;
        }

        location /img/ {
            alias /parking/static/img/;
            try_files $uri $uri/ =404;
            expires 30d;
        }

        location = /status {
            stub_status;
        }

        location /admin {
            proxy_pass http://pgadmin:80/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_set_header X-Script-Name /admin;
            proxy_set_header X-Forwarded-Prefix /admin;

            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;

            proxy_connect_timeout 300s;
            proxy_send_timeout 300s;
            proxy_read_timeout 300s;

            proxy_buffering off;
        }

        location /api/ {
            proxy_pass http://parking-api:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}